---
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - wget
        - gnupg

  - name: Add HashiCorp GPG key and repository
    shell: |
      wget -qO - https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

  - name: Update apt cache and install Consul
    apt:
      update_cache: yes
      name: consul
      state: present

  - name: Render Consul Configuration Template
    template:
      src: config.json.j2
      dest: /etc/consul.d/config.json
    vars:
      server: "false"
      datacenter: "dc1"

# template: This module is used to render Jinja2 templates.
# src: Specifies the source template file (config.json.j2), which likely contains variables and template logic.
# dest: Specifies the destination path for the rendered output (/etc/consul.d/config.json), where the final configuration file will be placed.
# vars: Defines variables that will be available to the template during rendering.
# server: Sets the value of the server variable to "false".
# datacenter: Sets the value of the datacenter variable to "dc1".
# This task will render the Consul configuration template (config.json.j2) 
# using the provided variables (server and datacenter) and place the 
# rendered output at /etc/consul.d/config.json. The template likely contains 
# placeholders for these variables, allowing for dynamic configuration generation based on the specified values.
  
  
  - name: Render Consul Backend Template
    template:
      src: backend.json.j2
      dest: /etc/consul.d/backend.json
  
  - name: Create Consul systemd service unit
    template:
      src: consul.service.j2
      dest: /etc/systemd/system/consul.service
    
  - name: Reload systemd
    systemd:
      daemon_reload: yes

  - name: Start and enable Consul service
    systemd:
      name: consul
      state: started
      enabled: yes


